server:
  port: 0 # 0 으로 설정하면 매번 랜덤값으로 port가 부여되어 실행되지만
  # 여러개의 클라이언트를 등록할수는 없으므로 eureka.instance.instance-id 설정이 반드시 명시되어야만 한다.
spring:
  application:
    name: user-service

eureka:

  client:
    fetch-registry: true # 유레카 서버로부터 인스턴스들의 정보를 주기적으로 가져올 것인지 설정. true이면 갱신된 정보를 받겠다는 뜻. 기본값은 true.
    register-with-eureka: true # 유레카 서버에 클라이언트를 등록시킬지 여부 설정. 기본값은 true.
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka # 유레카 서버 주소 지정
